# Generated by Django 3.2.3 on 2021-06-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('registrationNo', models.CharField(max_length=120)),
                ('cgpa', models.FloatField()),
            ],
        ),
    ]
