# Generated by Django 3.2.3 on 2021-06-03 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
